steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-f",
        "web/client/Dockerfile",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/web-client/web-client:${SHORT_SHA}",
        ".",
      ]

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/web-client/web-client:${SHORT_SHA}",
        "--region",
        "${_REGION}",
        "--project",
        "$PROJECT_ID",
        "--allow-unauthenticated",
        "--service-account",
        "${_RUN_SERVICE_ACCOUNT}",
        "--quiet",
        "--set-env-vars=DB_DRIVER=neon",
        "--set-secrets=DATABASE_URL=${_DATABASE_URL_SECRET}:latest,NEXTAUTH_URL=${_NEXTAUTH_URL_SECRET}:latest,NEXTAUTH_SECRET=${_NEXTAUTH_SECRET_SECRET}:latest,GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID_SECRET}:latest,GOOGLE_CLIENT_SECRET=${_GOOGLE_CLIENT_SECRET_SECRET}:latest",
      ]

images:
  - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/web-client/web-client:${SHORT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _SERVICE_NAME: "web-client-application"
  _REGION: "asia-northeast1"
  _RUN_SERVICE_ACCOUNT: "cloud-run-web-client@english-study-platform-staging.iam.gserviceaccount.com"
  _DATABASE_URL_SECRET: "database-url"
  _NEXTAUTH_URL_SECRET: "nextauth-url"
  _NEXTAUTH_SECRET_SECRET: "nextauth-secret"
  _GOOGLE_CLIENT_ID_SECRET: "google-client-id"
  _GOOGLE_CLIENT_SECRET_SECRET: "google-client-secret"
