name: Packages CI

on:
    push:
        branches:
            - main
        paths:
            - 'packages/**'
            - '.github/workflows/packages-ci.yml'
    pull_request:
        branches:
            - main
        paths:
            - 'packages/**'
            - '.github/workflows/packages-ci.yml'

jobs:
    packages:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: packages
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: pnpm
                  cache-dependency-path: packages/pnpm-lock.yaml

            - name: Install dependencies
              run: pnpm install --no-frozen-lockfile

            - name: Run Biome
              run: pnpm run lint

            - name: Type check
              run: pnpm run type-check

            - name: Test database connection
              run: |
                  # Create test environment file
                  cp .env.example .env
                  # Run migrations with test database
                  pnpm db:migrate || true
              env:
                  DB_DRIVER: local
                  DB_HOST: localhost
                  DB_PORT: "5432"
                  DB_NAME: test_db
                  DB_USER: postgres
                  DB_PASSWORD: postgres

        services:
            postgres:
                image: postgres:16-alpine
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_db
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5